[package]
name = "aoc_08"
version = "0.0.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = { workspace = true }

# Local
aoc_lib = { path = "../aoc_lib" }
